### ISSUE TITLE
Waiting for the code...

### ISSUE THREAD

**Issue by heitorrapela** [GeoVectorMatrix/Dif-Fusion#1]
Hello, 

I would like to know if you have plans to make the code open source,

Best Regards,

**Comment by DuyunliangToon** [comment]
Hello,
When will you upload the code? I am very interested in your article.
thanks

**Comment by PengFG** [comment]
Hello,
When will the code be released? Hope to see the code soon.
Best Regards

**Comment by GeoVectorMatrix** [comment]
updated

**Comment by heitorrapela** [comment]
Thanks @GeoVectorMatrix
