### ISSUE TITLE
很出色的工作，感谢作者！！！我在训练ddpm模型时遇到了点问题：

### ISSUE THREAD

**Issue by Supzekun** [GeoVectorMatrix/Dif-Fusion#10]
我使用MSRS数据集，train_ddpm.json训练新的ddpm.pth，然而似乎效果不好，loss函数是这样的：
![image](https://github.com/GeoVectorMatrix/Dif-Fusion/assets/53253522/217b36da-5313-4349-9eb8-c5e55c72b253)
请问训练时的超参数就是按照train_ddpm.json中设置的那样吗？大概需要训练多久呢，几天？

**Comment by GeoVectorMatrix** [comment]
For the DDPM part, the batch size depends on the GPU memory. It might be set to 10 for the 3090  (refer to the GPU monitor). A training session may take several days (e.g., >=6 days, >=6000 epochs with one 3090). We haven't extensively explored this part. Empirically, one may decide whether to stop training by inspecting the intermediate images generated during the training process.
