### ISSUE TITLE
很出色的工作，我想咨询一下有关代码的问题

### ISSUE THREAD

**Issue by 1580472223** [GeoVectorMatrix/Dif-Fusion#13]
在 diffusion.py文件下
```
    def predict_start_from_noise(self, x_t, t, noise):
        return self.sqrt_recip_alphas_cumprod[t] * x_t - \
            self.sqrt_recipm1_alphas_cumprod[t] * noise
```
我的理解是该函数用于预测X0，但原始推导中

``
![issue](https://github.com/GeoVectorMatrix/Dif-Fusion/assets/92093076/845e81a1-403f-41b3-9b25-084ace1a1fe8)

**Comment by 202230704080** [comment]
> 在 diffusion.py文件下
> 
> ```
>     def predict_start_from_noise(self, x_t, t, noise):
>         return self.sqrt_recip_alphas_cumprod[t] * x_t - \
>             self.sqrt_recipm1_alphas_cumprod[t] * noise
> ```
> 
> 我的理解是该函数用于预测X0，但原始推导中
> 
> `` ![issue](https://private-user-images.githubusercontent.com/92093076/323823482-845e81a1-403f-41b3-9b25-084ace1a1fe8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NTQ2NTgsIm5iZiI6MTcxNTY1NDM1OCwicGF0aCI6Ii85MjA5MzA3Ni8zMjM4MjM0ODItODQ1ZTgxYTEtNDAzZi00MWIzLTliMjUtMDg0YWNlMWExZmU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDAyMzkxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlMTBhY2E0YzYyNDI0Mjk1OGIxYTAyYjI2ZmU1MzQyMzQ2OTFmMmU4OGVlMTc2YTUzYjY2NDQyYjYxOWJjNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-S037s9x8EPEaUGsETYVqVQz89lFMj75rEzUNYZASTw)

这是用于求x0的，并不是xt
