### ISSUE TITLE
作者您好，关于训练fusion module时的batchsize，我有疑惑

### ISSUE THREAD

**Issue by Supzekun** [GeoVectorMatrix/Dif-Fusion#15]
在您的论文中，您标明训练fusion module时的batchsize为24，然而在您给出的训练代码：fusion_train.json中，batchsize为1。究竟哪个才是正确的？另外，我使用3090显卡进行训练，batchsize为24会爆显存，请问batchsize究竟是多少呢

**Comment by GeoVectorMatrix** [comment]
If I'm not mistaken，to train the fusion module, the input size for the networks  is 160*160 (after cropping), and then the batch size can be set to 24 for the 3090 GPU. The batch size 1 may have been used for testing the codes on a laptop.
