### ISSUE TITLE
Help! How do you deal with the image size problem in the RoadScene dataset which is not a multiple of 16

### ISSUE THREAD

**Issue by Jade999** [GeoVectorMatrix/Dif-Fusion#16]
In the denoising network, the input image is progressively downsampled to H/16 and W/16 using the U-net network. However, when using the RoadScene dataset for inference, since RoadScene contains 221 pairs of samples, most of their sizes are not multiples of 16 or 4. How do you handle this situation when using the RoadScene dataset

**Comment by GeoVectorMatrix** [comment]
When testing RoadScene dataset  (or other images of different sizes), the input image should be resized (e.g.,  640 x 480, 480 x 480...) before feeding to the network. After obtaining the fusion results from the model, resize it to the original size.
