### ISSUE TITLE
作者你好！关于文章的损失函数我有疑惑

### ISSUE THREAD

**Issue by salted55** [GeoVectorMatrix/Dif-Fusion#17]
文章提到的损失函数MCG和MCI都是传统梯度损失和强度损失的变体。我在查看代码的时候看到只有MCI是使用的多通道损失，MCG和灰度网络损失相同，是否是因为三通道的损失和单通道的损失相差不大呢。期待你的解惑，谢谢作者

**Comment by GeoVectorMatrix** [comment]
I think y_grad and ir_grad have 3 channels,  generate_img_grad and x_grad_joint also have 3 channels. [check the shapes of these tensors, each image may look like or can be converted to 3X160X160].
