### ISSUE TITLE
unable to download the pre-trained weights

### ISSUE THREAD

**Issue by tom-kh** [GeoVectorMatrix/Dif-Fusion#19]
unable to download the pre-trained weights file....

**Comment by GeoVectorMatrix** [comment]
Google Drive:

https://drive.google.com/drive/folders/1tmllPpxXmyXgfQ1A8M1fvVZIe7D5gsa2?usp=sharing

**Comment by tom-kh** [comment]
really appreciate for your quick response. Thank you so much. which one is used to replicate the results i think two files are there "fusion.pth" or "diffusion.pth"

**Comment by GeoVectorMatrix** [comment]
fusion.pth is for the fusion-head which outputs fused RGB images, and diffusion.pth is for the generation of diffusion-based features.

**Comment by tom-kh** [comment]
can i directly run your code for the testing on MSRS or M3FD dataset?

**Comment by GeoVectorMatrix** [comment]
I tested the code before, it works with weights. BTW, large-GPU(>=24G) is needed for large-images. We can also resize large-images to small ones (160*160/320*320) and feed them to GPU, then resize back for small-GPUs.

**Comment by MI-Hussain** [comment]
Can you please explain the steps where I need to modify the path to run the code? I tried but there is no documentation and clear explanation. Your help is requested, please.

**Comment by tom-kh** [comment]
> Can you please explain the steps where I need to modify the path to run the code? I tried but there is no documentation and clear explanation. Your help is requested, please.

I think you just need to adjust the path in the right place, give the pre-trained weights path in the config file, and test vi and ir image paths in the dataset.py file to run the code. I successfully ran it. Thank you for [GeoVectorMatrix](https://github.com/GeoVectorMatrix)
