### ISSUE TITLE
作者您好，请问加噪-去噪过程对融合网络的作用是什么？

### ISSUE THREAD

**Issue by Supzekun** [GeoVectorMatrix/Dif-Fusion#20]
如果去掉加噪-去噪的过程，会对融合结果产生什么影响？

**Comment by GeoVectorMatrix** [comment]
This process is designed to enable the network to learn a better joint distribution of multimodal data and to possess improved feature generalization capabilities. Removing this process would alter the technical framework, leading to a decline in performance under this framework. For a more detailed analysis and discussion, please refer to: D. Baranchuk, A. Voynov, I. Rubachev, V. Khrulkov, and A. Babenko, “Label-efficient semantic segmentation with diffusion models,” in Proc. Int. Conf. Learn. Represent. (ICLR), 2021, pp. 1–15.
