### ISSUE TITLE
about diffusion model

### ISSUE THREAD

**Issue by ccatian** [GeoVectorMatrix/Dif-Fusion#21]
作者您好，在您所提的框架中，往原始图像中加入噪声以及denoising network是不是共同构成diffusion model？此外denoising network的输出是什么？是否可以进行修改让其输出已生成的去噪后的高质量图像？ 因为我想使用这个模块仅用于图像去噪，不知是否可行，期待您的答复。

**Comment by GeoVectorMatrix** [comment]
The first question, the answer is Yes.

The second question is that it is a generative model that can generate/output various images (depends on the modallity of training dataset)

The third question, I guess you might prefer to refer to the Image  Denoising or  Restoration research, for example:
https://arxiv.org/pdf/2305.04457
https://github.com/yuanzhi-zhu/DiffPIR

**Comment by ccatian** [comment]
> The first question, the answer is Yes.
> 
> The second question is that it is a generative model that can generate/output various images (depends on the modallity of training dataset)
> 
> The third question, I guess you might prefer to refer to the Image Denoising or Restoration research, for example: https://arxiv.org/pdf/2305.04457 https://github.com/yuanzhi-zhu/DiffPIR

Thank you  for your reply and help！
