### ISSUE TITLE
Some qs about train model

### ISSUE THREAD

**Issue by crisych** [GeoVectorMatrix/Dif-Fusion#22]
In this file, the storage location of the trained diffusion model cannot be found，i can not find the .pth file,could you help?

**Comment by GeoVectorMatrix** [comment]
Can also be found in: https://github.com/GeoVectorMatrix/Dif-Fusion/issues/19#issuecomment-2149665140

**Comment by crisych** [comment]
No, I think you misunderstood my meaning. I want to train my own diffusion model and fusion model, but I cannot successfully save the'. pth' model file.
