### ISSUE TITLE
want to train my own model

### ISSUE THREAD

**Issue by crisych** [GeoVectorMatrix/Dif-Fusion#23]
Hello, I want to use my own dataset to train a diffusion model, but why is there no".pth"  file saved when run "train_ddpm.py"train_ddpm.py file, can you answer it for me? or teach me how to save it?

**Comment by crisych** [comment]
It's really bothered me for a long time，pls

**Comment by GeoVectorMatrix** [comment]
Please ref to the following lines, these may help: 

https://github.com/GeoVectorMatrix/Dif-Fusion/blob/2e7b4fcda579fa0008ef7db45857d418c35fa25c/models/model.py#L138


https://github.com/GeoVectorMatrix/Dif-Fusion/blob/2e7b4fcda579fa0008ef7db45857d418c35fa25c/train_ddpm.py#L136


https://github.com/GeoVectorMatrix/Dif-Fusion/blob/2e7b4fcda579fa0008ef7db45857d418c35fa25c/models/Fusion_model.py#L120


https://github.com/GeoVectorMatrix/Dif-Fusion/blob/2e7b4fcda579fa0008ef7db45857d418c35fa25c/train_fusion_head_msrs.py#L127



**Or learn from our code-base:**

https://github.com/wgcban/ddpm-cd/blob/f10eeb46cedb48b3ce6b5f79fb3660b551aa9a3a/model/model.py#L138

https://github.com/wgcban/ddpm-cd/blob/f10eeb46cedb48b3ce6b5f79fb3660b551aa9a3a/ddpm_train.py#L146



https://github.com/wgcban/ddpm-cd/blob/f10eeb46cedb48b3ce6b5f79fb3660b551aa9a3a/model/cd_model.py#L108

https://github.com/wgcban/ddpm-cd/blob/f10eeb46cedb48b3ce6b5f79fb3660b551aa9a3a/ddpm_cd.py#L312

**Comment by crisych** [comment]
i got it. thanks very very much.
