### ISSUE TITLE
训练过程疑问

### ISSUE THREAD

**Issue by DDKdakuan** [GeoVectorMatrix/Dif-Fusion#24]
我想问的是，在第二阶段训练fusion model时，所使用的训练好的U-Net（去噪网络）可以输出一个符合人眼逻辑的图像吗，还是仅仅是高维特征的映射，表现出来为抽象的像素集合

**Comment by 225ceV** [comment]
我也想问这个问题

**Comment by DDKdakuan** [comment]
> 我也想问这个问题

从代码上看他是在隐空间进行的，所以理论上那是一个特征集合

**Comment by GeoVectorMatrix** [comment]
1.  We are using high-dimensional features, which cannot be visualized as normal images.
2. The trained Diffusion model can generate images from different channels. If I remember correctly, the code is similar to this: https://github.com/GeoVectorMatrix/Dif-Fusion/blob/37b64eedde53687385ab08f3f6137058ddc4736a/models/model.py#L123
