### ISSUE TITLE
有关对比实验的一些问题

### ISSUE THREAD

**Issue by 1580472223** [GeoVectorMatrix/Dif-Fusion#25]
在您的文章中提到，所使用的对比方法是直接采用的开源代码以及预训练模型。这样的实验设置是否比在同一数据集上训练更加合理？

**Comment by GeoVectorMatrix** [comment]
Open source codes and  pre-trained weights are generally provied by the authors. We think that using these pre-trained models would be objective and acceptable.
﻿
Some models may have been trained on multiple datasets (or with different settings)  to achieve better results. We did not analyze these methods individually, and we agree that your suggetion is beneficial.
