### ISSUE TITLE
json文件求助

### ISSUE THREAD

**Issue by shelter08** [GeoVectorMatrix/Dif-Fusion#28]
请问作者训练扩散模型的代码，在py文件中改了训练集路径，json文件中的TBD需要改吗？TBD是什么意思呢？期待回复

**Comment by GeoVectorMatrix** [comment]
TBD means to be determined. To re-train ddpm, it needs to be set to the path where the dataset is located.

**Comment by shelter08** [comment]
请问除了json文件的那个路径，为了重新训练还需要更改哪些内容呢？

**Comment by shelter08** [comment]
请问除了json文件的那个路径，为了重新训练还需要更改哪些内容呢？
