### ISSUE TITLE
code not run

### ISSUE THREAD

**Issue by yudongjian** [GeoVectorMatrix/Dif-Fusion#3]
Hello :
 
     code not run,
     because  some fun not defined.  even not in   [ddpm-cd](https://github.com/wgcban/ddpm-cd)
   eg,    
![image](https://github.com/GeoVectorMatrix/Dif-Fusion/assets/78006669/57c2423f-23d9-405a-b1ae-85cb2c4eb017)
  hope get your help, thanks!

**Comment by GeoVectorMatrix** [comment]
Updated in util.py
