### ISSUE TITLE
最后test的时候显示输入维数不对

### ISSUE THREAD

**Issue by zerathluuuuuu** [GeoVectorMatrix/Dif-Fusion#32]
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 36 but got size 35 for tensor number 1 in the list.
![5533745158](https://github.com/user-attachments/assets/c567d767-fc1a-4554-9ca8-0490810ff159)

**Comment by GeoVectorMatrix** [comment]
Maybe, it relates to the input-size. Please refer to : https://github.com/GeoVectorMatrix/Dif-Fusion/issues/16#issuecomment-2081775896
